[package]
name = "taskmaster"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2.172"
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1.44.2", features = ["full"] }
toml = "0.8.15"
