[package]
name = "taskmaster"
version = "0.1.0"
edition = "2021"

[profile.release]
panic = "abort"

[profile.dev]
panic = "abort"

[dependencies]
serde = "1.0.204"
serde_derive = "1.0.204"
toml = "0.8.15"
