[programs.sleep20]
command = "sleep"
args = ["20"]
autostart = true
autorestart = "never"
stopsignal = "TERM"
stdout = "/dev/stdout"
stderr = "/dev/stderr"
time_success = 1
nbr_restart = 0
time_kill = 1

[programs.sleep7]
command = "sleep"
args = ["7"]
autostart = true
autorestart = "never"
stopsignal = "TERM"
stdout = "/dev/stdout"
stderr = "/dev/stderr"
time_success = 1
nbr_restart = 0
time_kill = 1

[global]
logfile = "./logfile.log"
