[programs.sleep20]
command = "sleep"
args = ["20"]
autostart = true
autorestart = "never"
stopsignal = "TERM"
stdout = "/dev/stdout"
stderr = "/dev/stderr"

[programs.sleep7]
command = "sleep"
args = ["7"]
autostart = true
autorestart = "never"
stopsignal = "TERM"
stdout = "/dev/stdout"
stderr = "/dev/stderr"

[global]
logfile = "./logfile.log"
